const users = [
  {
    _id: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
    name: 'Charles Dickens',
    email: 'charles@email.com',
    picture: '',
  },
  {
    _id: '1b9d6bcd-bbfc-4b2d-5f7r-ab8dfbhnekw2',
    name: 'William Shakespeare',
    email: 'william@email.com',
    picture: '',
  },
  {
    _id: '1b9d7bcd-cbfd-4b2d-5b6d-ab8dfdbv4bed',
    name: 'Stephen King',
    email: 'stephen@email.com',
    picture: '',
  },
  {
    _id: '1b9d7bcd-cbfd-4b2d-5b6d-y86rt363tdt3',
    name: 'Haruki Murakami',
    email: 'haruki@email.com',
    picture: '',
  },
  {
    _id: '64194316-d285-4ca2-b2a3-c6a6ed5e59da',
    name: 'Robert Kiyosaki',
    email: 'robertk@email.com',
    picture: '',
  },
];

const books = [
  {
    _id: '1',
    author: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
    title: 'Oliver Twist',
    cover_image:
      'https://images-na.ssl-images-amazon.com/images/I/81QGqaKWjXL.jpg',
    pages: 234,
    releaseDate: '1839',
    isbn: 'wt345',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Novel', 'Fiction', 'Social novel'],
  },
  {
    _id: '2',
    author: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
    title: 'Hard Times',
    cover_image:
      'https://rukminim1.flixcart.com/image/416/416/k5si2kw0/regionalbooks/k/k/t/charles-dickens-hard-times-original-imafzekkhmzbcvzm.jpeg?q=70',
    pages: 300,
    releaseDate: '1854',
    isbn: 'jk654',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Novel', 'Fiction', 'Industrial novel'],
  },
  {
    _id: '3',
    author: '1b9d6bcd-bbfc-4b2d-5f7r-ab8dfbhnekw2',
    title: 'Hamlet',
    cover_image:
      'https://kbimages1-a.akamaihd.net/695eb39e-9405-4c4b-8267-302344f0f5f7/1200/1200/False/hamlet-15.jpg',
    pages: 160,
    releaseDate: '1603',
    isbn: 'po789',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Tragedy', 'Drama'],
  },
  {
    _id: '4',
    author: '1b9d7bcd-cbfd-4b2d-5b6d-ab8dfdbv4bed',
    title: 'IT',
    cover_image: '',
    pages: 500,
    releaseDate: '2017',
    isbn: 'yu098',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Horror', 'Thriller', 'Dark fantasy'],
  },
  {
    _id: '5',
    author: '1b9d7bcd-cbfd-4b2d-5b6d-y86rt363tdt3',
    title: 'Norwegian Wood',
    cover_image:
      'http://t1.gstatic.com/images?q=tbn:ANd9GcQvJJDi2mzwg9v_PlmKYL31gXIz0kvAObJak7DVFPcD_mJTIyec',
    pages: 296,
    releaseDate: '1987',
    isbn: 'hj846',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Novel', 'Romance novel', 'Bildungsroman', 'Literary fiction'],
  },
  {
    _id: '6',
    author: '1b9d7bcd-cbfd-4b2d-5b6d-y86rt363tdt3',
    title: 'Kafka on the Shore',
    cover_image:
      'http://t0.gstatic.com/images?q=tbn:ANd9GcRHFU_j93PPsbQGqoaZJnHH6-Emk_sIxG823SkoRTL0nvdEP41f',
    pages: 505,
    releaseDate: '2002',
    isbn: 'op012',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Novel', 'Magical Realism', 'Fantasy Fiction'],
  },
  {
    _id: '7',
    author: '1b9d7bcd-cbfd-4b2d-5b6d-y86rt363tdt3',
    title: 'After Dark',
    cover_image:
      'http://t3.gstatic.com/images?q=tbn:ANd9GcQBMNA8A19vQpNY4bkgadsLhiRUFqBKwKAA6ANrw8VEtOiPrYQJ',
    pages: 208,
    releaseDate: '2004',
    isbn: 'cv456',
    wishListedBy: [],
    subscribedBy: [],
    category: ['Novel', 'Fiction'],
  },
  {
    _id: '8',
    author: '64194316-d285-4ca2-b2a3-c6a6ed5e59da',
    title: 'Rich Dad and Poor Dad',
    cover_image: 'https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg',
    pages: 240,
    releaseDate: '1997',
    isbn: 'al207',
    wishListedBy: [],
    subscribedBy: [],
    category: ['finance', 'fiction'],
  },
];

module.exports = { users, books };
